services:
  imagen1-rpm:
    build:
      context: .
      dockerfile: "Imagen#1/Dockerfile"
    image: bkbigmac/proyectofinal2:imagen1
    container_name: rpm-env
    tty: true
    stdin_open: true

  imagen2-ruby:
    build:
      context: .
      dockerfile: "Imagen#2/Dockerfile"
    image: bkbigmac/proyectofinal2:imagen2
    container_name: ruby-env
    tty: true
    stdin_open: true

  imagen3-node:
    build:
      context: .
      dockerfile: "Imagen#3/Dockerfile"
    image: bkbigmac/proyectofinal2:imagen3
    container_name: node-env
    tty: true
    stdin_open: true

  imagen4-python:
    build:
      context: .
      dockerfile: "Imagen#4/Dockerfile"
    image: bkbigmac/proyectofinal2:imagen4
    container_name: python-env
    tty: true
    stdin_open: true

  imagen5-full:
    build:
      context: .
      dockerfile: "Imagen#5/Dockerfile"
    image: bkbigmac/proyectofinal2:imagen5
    container_name: full-stack-env
    tty: true
    stdin_open: true



